#!/bin/sh

#
# Copy to PROJECT_ROOT/.git/hooks/pre-commit
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

#
# Validate PHP syntax
#
ROOT_DIR="$(pwd)/"
LIST=
IS_PHP_SYNTAX_ERROR=0
# (A)dded, (C)opied, (M)odified, (R)renamed
for file in $(git diff-index --cached --name-only --diff-filter=ACMR HEAD \
    | awk '/\.php$/{print}')
do
    ERRORS=$(php -l $ROOT_DIR$file 2>&1)
    if [ $? != 0 ]; then
        echo $ERRORS
	IS_PHP_SYNTAX_ERROR=1
    fi
done
if [ $IS_PHP_SYNTAX_ERROR -gt 0 ]; then
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
